POST http://localhost:1234/cgi/test.pl
Content-Type: text/plain

Hello, world!
###
POST http://localhost:1234/cgi/body_echo.lua

Hello, world!
###
POST http://localhost:1234/cgi/body_echo.lua

small
###
GET http://www.nginx.com/
User-Agent: garbage